name: 'File Lint'
description: |
  Lint various files in many ways (CR / CRLF / trailing \n / etc)

  To save space in workflow files, its possible to use the matrix to run this job multiple times with a different command. Eg:

    strategy:
      matrix:
        command:
          - cr
          - crlf
    steps:
      - uses: actions/checkout@master
      - uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-${{ matrix.command }}

inputs:
  command:
    description: |
        The specific command to be run.

        ##### Available Commands

        - cr: Scan files and check if they contain CR (Carriage Return only).
        - crlf: Scan files and check if they contain CRLF (Windows Line Feeds).
        - empty: Scan files and check if they are empty (0 bytes).
        - nullbyte-char: Scan files and check if they contain a null-byte character (\x00).
        - trailing-newline: Scan files and check if they contain a trailing newline.
        - trailing-single-newline: Scan files and check if they contain exactly one trailing newline.
        - trailing-space: Scan files and check if they contain trailing whitespaces.
        - utf8: Scan files and check if they have a non UTF-8 encoding.
        - utf8-bom: Scan files and check if they contain BOM (Byte Order Mark): <U+FEFF>.
    required: true
  path:
    description: |
      The path to the repository that will be checked. Defaults to the location of `actions/checkout` default path.
    required: false
    default: /github/workspace
  ignore:
    description: 'List of paths to be ignored'
    required: false
    default: .git
runs:
  using: 'docker'
  image: 'Dockerfile'
